---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    install_config: "{{ lookup('file', install_config_file) | from_yaml }}"
    install_config_file: install-config.yaml
#    install_config: "/root/ocp43/install-config.yaml"
    cluster_name: "{{ install_config.metadata.name }}"
    node_role: "compute"
    idx: "3"
    ip: 192.168.3.187
    gateway: 192.168.3.1
    cidr_prefix: 24
    dns_server: 192.168.3.101
#    master_ign_file: "{{ cluster_name }}/master.ign"
    worker_ign_file: "{{ cluster_name }}/worker.ign"
#    bootstrap_ign_file: "{{ cluster_name }}/bootstrap.ign"
#    http_document_root: /var/www/html/ignitions
#   bootstrap_ignition_config_url: "http://{{ httpd_ip }}/ignitions/{{cluster_name}}_bootstrap.ign"
  tasks:

  - name: Set node role to compute
    set_fact:
      node_role: compute
      ignition_template: node.ign

  - name: Read worker ignition config
    set_fact:
      ignition_data: "{{ lookup('file', worker_ign_file) }}"



  - name: Generate network configuration of "{{ node_role }}"- "{{ idx }}"
    set_fact:
      node_name: "{{ cluster_name }}-{{ node_role }}-{{ idx }}"
      network_config: |
        TYPE=Ethernet
        BOOTPROTO=none
        NAME=ens192
        DEVICE=ens192
        ONBOOT=yes
        IPADDR={{ ip }}
        PREFIX={{ cidr_prefix }}
        GATEWAY={{ gateway }}
        DOMAIN={{ install_config.baseDomain }}
        DNS1={{ dns_server }}

  - name: Clone the template
    vmware_guest:
       hostname: "{{ install_config.platform.vsphere.vcenter }}"
       username: administrator@vsphere.local
       password: XXXXXXXX
       validate_certs: no
       datacenter: KonsaltDC
       folder: ocp
       state: present
       name: ocp-compute-3
       template: rhcos43
    register: deploy

  - name: Configure vApp properties of {{ node_name }}
    vmware_guest:
      hostname: "{{ install_config.platform.vsphere.vcenter }}"
      username: "{{ install_config.platform.vsphere.username }}"
      password: "{{ install_config.platform.vsphere.password }}"
      validate_certs: no
      uuid: "{{ deploy.instance.hw_product_uuid }}"
      state: present
      vapp_properties:
        - id: "guestinfo.ignition.config.data"
          value: "{{ lookup('template', ignition_template ) | to_nice_json(indent=2) | b64encode }}"
        - id: "guestinfo.ignition.config.data.encoding"
          value: base64
        - id: "disk.EnableUUID"
          value: "TRUE"

  - name: Power ON {{ node_name }}
    vmware_guest:
      hostname: "{{ install_config.platform.vsphere.vcenter }}"
      username: "{{ install_config.platform.vsphere.username }}"
      password: "{{ install_config.platform.vsphere.password }}"
      validate_certs: no
      uuid: "{{ deploy.instance.hw_product_uuid }}"
      state: poweredon
